#!/bin/sh
lock() {
    i3lock
}

case "$1" in

    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {reboot|shutdown}"
        exit 2
esac

exit 0
